#!/usr/bin/env bash

ps cax | grep yabai > /dev/null
if [ $? -eq 0 ]; then
	a+=$(/usr/local/bin/yabai -m query --spaces --space | grep index | cut -f2- -d: | cut -d',' -f1)
	a+=' '
	a+=$(/usr/local/bin/yabai -m query --spaces --space | grep label|cut -f2- -d:| rev | cut -c3- | rev|cut -c 2-)	
	echo -e $a
else 
	ps cax | grep chunkwm > /dev/null
	if [ $? -eq 0 ]; then
	  /usr/local/bin/chunkc tiling::query --desktop id
	else
		echo ""
	fi
fi
